Repository kidnapping-group/TravelMaker, pull requests merged in 2024-08, with the labels that each got.

#21 chore: tailwindcss config 수정 (ST-45)
  src/components/Button.tsx
  tailwind.config.ts
Labels: :package: CHORE

#23 remove: husky pre-push 훅 (ST-46)
  .husky/pre-push
Labels: :fire: REMOVE

#17 feat: 페이지네이션 구현(ST-9)
  public/icons/icon-arrow-next-passive-pagination.svg
  public/icons/icon-arrow-prev-pagination.svg
  public/icons/icon-arrow-prev-passive-pagination.svg
  src/components/Pagination.tsx
  src/hooks/useViewport.tsx
Labels: :sparkles: FEATURE

#22 feat: API 로직 구현(ST-14)
  .eslintrc.json
  package.json
  pnpm-lock.yaml
  src/apis/API.type.ts
  src/apis/ApiError.ts
  src/apis/activitiesAPI.ts
  src/apis/authAPI.ts
  src/apis/axiosInstance.ts
  src/apis/myActivitiesAPI.ts
  src/apis/myNotificationsAPI.ts
  src/apis/myReservationAPI.ts
  src/apis/usersAPI.ts
Labels: :sparkles: FEATURE

#26 feat: not found page 구현(ST-28)
  public/images/404.png
  src/app/[...not_found]/page.tsx
  src/app/error.tsx
  src/app/page.tsx
Labels: :sparkles: FEATURE

#14 feat: 드롭 다운 구현(ST-11)
  .husky/pre-commit
  public/icons/icon-dropup.svg
  src/components/Dropdown.tsx
Labels: :sparkles: FEATURE

#27 chore: test 폴더 체크하는 상태 검사 추가
  .github/workflows/check-test-folder.yml
Labels: :package: CHORE

#29 feat: nextconfig domain(ST-50)
  .husky/pre-commit
  next.config.mjs
Labels: :sparkles: FEATURE

#31 refactor: 단일값 받는 파일 params 제거(ST-51)
  src/apis/API.type.ts
  src/apis/activitiesAPI.ts
  src/apis/myNotificationsAPI.ts
  src/apis/myReservationAPI.ts
Labels: :recycle: REFACTOR

#24 feat 공통 Input 컴포넌트 구현(ST-8)
  package.json
  pnpm-lock.yaml
  src/app/error.tsx
  src/components/Input/Input.tsx
  src/components/Input/TextArea.tsx
  src/components/Input/getInputColorStatus.ts
  src/components/Pagination.tsx
  src/utils/schema.ts
Labels: :sparkles: FEATURE

#39 fix: api 오류 수정 및 tailwind 색상추가(ST-53)
  src/apis/API.type.ts
  src/apis/axiosInstance.ts
  src/app/globals.css
  tailwind.config.ts
Labels: :bug: FIX

#28 feat: notification (ST-10)
  public/icons/icon-exist-notification.svg
  src/apis/API.type.ts
  src/app/_components/Header.tsx
  src/app/_components/Notification/AlertItem.tsx
  src/app/_components/Notification/index.tsx
  src/components/Input/Input.tsx
  src/components/Input/TextArea.tsx
  src/utils/formatTime.ts
Labels: :sparkles: FEATURE

#41 feat: 체험 상세 페이지 초기 세팅(ST-52)
  src/app/[activityId]/_components/ActivityIdDetail.tsx
  src/app/[activityId]/_components/Review.tsx
  src/app/[activityId]/activityId.ts
  src/app/[activityId]/page.tsx
  src/app/favicon.ico
  src/app/layout.tsx
  src/contexts/ReactQueryProviders.tsx
Labels: :sparkles: FEATURE

#43 faet: ActivityID페이지의 ActivityDetail 컴포넌트 구현 (St-57)
  package.json
  pnpm-lock.yaml
  public/icons/icon-meatball.svg
  public/icons/icon-next.svg
  public/icons/icon-prev.svg
  src/app/[activityId]/_components/ActivityIdDetail.tsx
  src/app/[activityId]/_components/Map.tsx
  src/app/_components/Header.tsx
  src/contexts/ReactQueryProviders.tsx
Labels: :sparkles: FEATURE

#40 chore: prettier pnpm-lock.yaml 파일 제외 (ST-54)
  .prettierignore
  src/apis/axiosInstance.ts
Labels: :package: CHORE

#44 feat: activity page review영역 완성
  package.json
  pnpm-lock.yaml
  src/app/[activityId]/_components/ActivityIdDetail.tsx
  src/app/[activityId]/_components/Review.tsx
  src/components/Pagination.tsx
Labels: :sparkles: FEATURE

#48 feat:로그인 페이지 기초 logic(ST-59)
  src/app/(auth)/signin/page.tsx
Labels: :sparkles: FEATURE

#19 feat: Popup 구현 (ST-4)
  src/app/components/Popup.tsx
Labels: :sparkles: FEATURE

#49 fix: Popup 컴포넌트 위치 수정 (ST-61)
  src/components/Popup.tsx
Labels: :bug: FIX

#46 feat: Swiper 컴포넌트 구현 (ST-44)
  package.json
  pnpm-lock.yaml
  src/components/Swiper/Button.tsx
  src/components/Swiper/Context.tsx
  src/components/Swiper/index.tsx
Labels: :sparkles: FEATURE

#50 fix: 변경된 파일이 없을 경우 husky pre commit 에러 수정 (ST-62)
  .husky/pre-commit
Labels: :bug: FIX

#52 feat: popup 추가 및 css 적용(ST-63)
  public/icons/icon-google.svg
  public/icons/icon-kakao.svg
  public/images/logo_big.png
  src/app/(auth)/layout.tsx
  src/app/(auth)/signin/page.tsx
Labels: :sparkles: FEATURE

#54 feat: Oauth api 추가(ST-71)
  src/apis/API.type.ts
  src/apis/OauthAPI.ts
Labels: :sparkles: FEATURE

#57 refactor: api type 세분화(ST-73)
  src/apis/API.type.ts
Labels: :recycle: REFACTOR

#60 refactor: 유저 값 없을 시 로그인페이지로 이동
  src/app/(user)/layout.tsx
Labels: :recycle: REFACTOR

#53 feat: 회원가입 페이지(ST-64)
  src/apis/usersAPI.ts
  src/app/(auth)/layout.tsx
  src/app/(auth)/signup/page.tsx
  src/utils/schema.ts
Labels: :sparkles: FEATURE

#55 feat: 구글 소셜 회원가입 추가(ST-66)
  src/app/(auth)/social/google/page.tsx
Labels: :sparkles: FEATURE

#56 feat: 카카오 소셜 회원가입 추가(ST-72)
  src/app/(auth)/social/kakao/page.tsx
Labels: :sparkles: FEATURE

#59 feat: 소셜로그인 리다이렉팅 로직 추가(ST-74)
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(auth)/social/google/page.tsx
  src/app/(auth)/social/kakao/page.tsx
  src/store/kakaoSocialStatusStore.ts
Labels: :sparkles: FEATURE

#61 refactor: api 타입 수정(ST-81)
  src/apis/API.type.ts
  src/apis/usersAPI.ts
Labels: :recycle: REFACTOR

#67 refactor: modal 열고 닫는 거 부모에서 조정 가능, popup 8-14 스크럼 안건 사항 반영(ST-91)
  src/app/(auth)/signin/page.tsx
  src/app/globals.css
  src/components/Modal.tsx
  src/components/Popup.tsx
Labels: :recycle: REFACTOR

#68 feat: 로그인시 상태값 받아 쿠키에저장(ST-93)
  src/apis/OauthAPI.ts
  src/apis/authAPI.ts
  src/store/socialLoginStore.ts
Labels: :sparkles: FEATURE

#74 hotfix: mypage layout(ST-98)
  src/app/(user)/layout.tsx
Labels: :bug: FIX

#76 style: 모달 높이 자유롭게, 너비 460, font크기 수정(ST-100)
  src/components/Modal.tsx
Labels: :lipstick: STYLE

#77 style: 오른쪽 버튼이 파랗게 빛나게 수정(ST-102)
  src/components/Popup.tsx
Labels: :lipstick: STYLE

#64 feat: 메인 페이지 인기 체험 구현 (ST-69)
  public/icons/star.svg
  src/app/_components/BigActivityCard.tsx
  src/app/_components/BigActivitySection.tsx
  src/app/page.tsx
Labels: :sparkles: FEATURE

#65 feat: 메인 페이지 체험 리스트 구현 (ST-70)
  src/app/_components/ActivityCard.tsx
  src/app/_components/ActivitySection.tsx
  src/app/page.tsx
Labels: :sparkles: FEATURE

#9 feat: Footer 구현(ST-6)
  src/app/_components/Footer.tsx
  src/app/layout.tsx
Labels: :sparkles: FEATURE, :lock: HOLD

#51 feat: my activity page 완성(ST-55)
  public/images/spinner.png
  src/app/(user)/layout.tsx
  src/app/(user)/myactivities/_components/ContextMenu.tsx
  src/app/(user)/myactivities/_components/MyActivities.tsx
  src/app/(user)/myactivities/_components/MyActivityItem.tsx
  src/app/(user)/myactivities/page.tsx
Labels: :sparkles: FEATURE

#72 feat: 토큰만료시 로그인페이지로 이동(ST-92)
  src/apis/axiosInstance.ts
  src/app/(auth)/signin/page.tsx
Labels: :sparkles: FEATURE

#75 fix: useMediaQuery 훅 생성 및 로딩시 네비게이션 레이아웃 오류 수정(ST-99)
  src/app/(user)/_components/Navigation.tsx
  src/hooks/useMediaQuery.tsx
  src/hooks/useViewport.tsx
Labels: :bug: FIX

#78 fix: 로고에 메인페이지 이동link 추가(ST-103)
  src/app/(auth)/signin/page.tsx
Labels: :bug: FIX

#79 fix: 회원가입 페이지 팝업추가(ST-104)
  src/app/(auth)/signup/page.tsx
Labels: :bug: FIX

#80 fix: 타입 수정(ST-105)
  src/apis/API.type.ts
Labels: :bug: FIX

#62 feat: 예약내역 페이지 로직 & 페이지 css 추가(ST-84)
  src/app/(user)/layout.tsx
  src/app/(user)/reservations/_components/MyReservationItem.tsx
  src/app/(user)/reservations/_components/MyReservations.tsx
  src/app/(user)/reservations/page.tsx
Labels: :sparkles: FEATURE

#84 chore: 커밋 메세지 제목 제한 50자에서 80자로 늘림 (ST-107)
  .husky/commit-msg
Labels: :package: CHORE

#73 feat: 유저상태의 헤더 ui 구현 ST-97
  public/icons/noProfile.svg
  src/app/_components/Header.tsx
  src/app/_components/Header/Dropdown.tsx
  src/app/_components/Header/DynamicHeader.tsx
  src/app/_components/Header/UserExist.tsx
  src/app/_components/Header/UserNotExist.tsx
  src/app/_components/Header/index.tsx
  src/hooks/useDropdownToggle.tsx
  src/store/socialLoginStore.ts
  src/utils/getUserInfoFromCookie.ts
  src/utils/logout.ts
Labels: :sparkles: FEATURE

#83 style: Swiper & Card 스타일 수정 (ST-106)
  src/app/_components/ActivityCard.tsx
  src/app/_components/BigActivityCard.tsx
  src/components/Swiper/index.tsx
Labels: :lipstick: STYLE

#81 feat: 메인 페이지 배너 구현 (ST-68)
  src/app/(user)/myactivities/_components/MyActivityItem.tsx
  src/app/_components/Banner.tsx
  src/app/_components/Carousel.tsx
  src/app/page.tsx
Labels: :sparkles: FEATURE

#69 feat: 예약내역 페이지 카드 생성및 예약취소 로직(ST-82)
  src/app/(user)/layout.tsx
  src/app/(user)/reservations/_components/MyReservationItem.tsx
  src/app/(user)/reservations/_components/MyReservations.tsx
  src/app/(user)/reservations/_components/review/Review.tsx
Labels: :sparkles: FEATURE

#71 feat: 리뷰모달 작성(ST-94)
  src/app/(user)/reservations/_components/review/Rating.tsx
  src/app/(user)/reservations/_components/review/Review.tsx
Labels: :sparkles: FEATURE

#85 feat: ActivitySection의 Swiper 버튼 위치 변경 (ST-108)
  src/app/_components/ActivitySection.tsx
  src/app/_components/BigActivitySection.tsx
  src/components/Swiper/Button.tsx
  src/components/Swiper/Content.tsx
  src/components/Swiper/Context.tsx
  src/components/Swiper/index.tsx
Labels: :sparkles: FEATURE

#87 fix: 등록 url 수정(ST-110)
  src/app/(user)/myactivities/_components/MyActivities.tsx
Labels: :bug: FIX

#70 feat: activity page(ST-25)
  public/icons/icon-add.svg
  public/icons/icon-minus.svg
  public/images/noImage.png
  src/apis/API.type.ts
  src/app/(user)/myactivities/add/page.tsx
  src/app/[activityId]/_components/ActivityIdDetail.tsx
  src/app/[activityId]/_components/Contents.tsx
  src/app/[activityId]/_components/Header/DropdownMenu.tsx
  src/app/[activityId]/_components/Header/DropdownMenuPopup.tsx
  src/app/[activityId]/_components/Header/index.tsx
  src/app/[activityId]/_components/Images.tsx
  src/app/[activityId]/_components/MobileFooter.tsx
  src/app/[activityId]/_components/ReservationModal.tsx
  src/app/[activityId]/_components/ReservationSteps/Calendar/CalendarDay.tsx
  src/app/[activityId]/_components/ReservationSteps/Calendar/index.tsx
  src/app/[activityId]/_components/ReservationSteps/FreeReservationTime.tsx
  src/app/[activityId]/_components/ReservationSteps/ReservationButton.tsx
  src/app/[activityId]/_components/ReservationSteps/TotalMoney.tsx
  src/app/[activityId]/_components/ReservationSteps/index.tsx
  src/app/[activityId]/_components/Review.tsx
  src/app/[activityId]/_components/Review/CommentList.tsx/Comment.tsx
  src/app/[activityId]/_components/Review/CommentList.tsx/index.tsx
  src/app/[activityId]/_components/Review/ReviewDetail.tsx
  src/app/[activityId]/_components/Review/index.tsx
  src/app/[activityId]/_contexts/ActivityIdContext.tsx
  src/app/[activityId]/_hooks/useActivityPopulation.ts
  src/app/[activityId]/_hooks/useControlDropdownMenu.ts
  src/app/[activityId]/_hooks/useControlPopup.ts
  src/app/[activityId]/_hooks/useDeleteActivityMutation.ts
  src/app/[activityId]/_hooks/useGetActivityContentsViewModel.ts
  src/app/[activityId]/_hooks/useGetActivityFooterViewModel.ts
  src/app/[activityId]/_hooks/useGetActivityHeaderViewModel.ts
  src/app/[activityId]/_hooks/useGetActivityImagesViewModel.ts
  src/app/[activityId]/_hooks/useGetActivityReservationStepsViewModel.ts
  src/app/[activityId]/_hooks/useGetCommentItemViewModel.ts
  src/app/[activityId]/_hooks/useGetCommentReviewViewModel.ts
  src/app/[activityId]/_hooks/usePostReservationMutation.ts
  src/app/[activityId]/_utils/createCalendar.ts
  src/app/[activityId]/_utils/getActivityData.ts
  src/app/[activityId]/_utils/getCommentData.ts
  src/app/[activityId]/_utils/getCookies.ts
  src/app/[activityId]/_utils/isReservationAvailable.ts
  src/app/[activityId]/activityId.ts
  src/app/[activityId]/page.tsx
  src/app/[activityId]/queryOptions.ts
  src/hooks/useImageError.ts
  src/utils/formatKoreanWon.ts
Labels: :sparkles: FEATURE

#89 feat: 검색 페이지 구현 (ST-67)
  src/app/search/_components/ActivityGrid.tsx
  src/app/search/_components/SortDropdown.tsx
  src/app/search/_components/TabList/Tab.tsx
  src/app/search/_components/TabList/index.tsx
  src/app/search/page.tsx
  src/hooks/useUpdateQuery.ts
Labels: :sparkles: FEATURE

#90 fix: 페이지네이션 버튼 누르면 기존 query가 사라지는 문제 (ST-118)
  src/components/Pagination.tsx
Labels: :bug: FIX

#91 style: Pagination 스타일 수정 (ST-119)
  src/components/Pagination.tsx
Labels: :lipstick: STYLE

#88 fix: (user) layout 수정(ST-79)
  src/app/(auth)/layout.tsx
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/_components/Footer.tsx
Labels: :recycle: REFACTOR

#92 refactor: 마감완료 생성 및 무한스크롤 구현(ST-121)
  src/apis/API.type.ts
  src/app/(user)/reservations/_components/MyReservationItem.tsx
  src/app/(user)/reservations/_components/MyReservations.tsx
Labels: :recycle: REFACTOR

#94 feat: 메인페이지 체험섹션 더보기 버튼 추가 (ST-122)
  src/app/_components/ActivitySection.tsx
  src/app/search/page.tsx
  src/utils/createQueryString.ts
Labels: :sparkles: FEATURE

#93 feat: 검색창에 검색 내용 표시 & 입력값 없을 때 검색 방지 (ST-116)
  src/app/_components/SearchForm.tsx
  src/components/Tooltip.tsx
  tailwind.config.ts
Labels: :sparkles: FEATURE

#99 fix: 헤더 데이터 페칭 방식 변경, 로그아웃 시 메인으로, 마이페이지(account).(ST-130)
  src/apis/OauthAPI.ts
  src/apis/authAPI.ts
  src/app/(home)/page.tsx
  src/app/_components/Header/Dropdown.tsx
  src/app/_components/Header/DynamicHeader.tsx
  src/app/_components/Header/UserExist.tsx
  src/app/_components/Header/index.tsx
  src/store/socialLoginStore.ts
  src/utils/logoutCookies.ts
Labels: :bug: FIX

#82 feat: 내 정보 페이지 구현 (ST-27)
  public/icons/icon-back.svg
  public/icons/icon-pen.svg
  public/icons/icon-profile.svg
  public/images/defaultProfile.png
  src/apis/API.type.ts
  src/app/(auth)/social/google/page.tsx
  src/app/(auth)/social/kakao/page.tsx
  src/app/(user)/account/_component/ProfileEditor.tsx
  src/app/(user)/account/page.tsx
  src/app/(user)/layout.tsx
  src/components/Input/Input.tsx
  src/components/Input/getInputColorStatus.ts
  src/utils/schema.ts
Labels: :sparkles: FEATURE

#98 feat: Dropdown 스타일 통일 (ST-114)
  src/app/(home)/search/_components/SortDropdown.tsx
  src/app/(user)/reservations/_components/MyReservations.tsx
  src/components/Dropdown.tsx
Labels: :sparkles: FEATURE

#100 refactor: 페이지네이션 버튼 컴포넌트 분리 (ST-128)
  src/components/Pagination.tsx
  src/components/Pagination/Button.tsx
  src/components/Pagination/index.tsx
Labels: :recycle: REFACTOR

#102 feat: Notification 스타일 수정 & 색 적용 안되는 문제 고침 (ST-132)
  public/icons/icon-ellipse-blue.svg
  public/icons/icon-ellipse-gary.svg
  public/icons/icon-ellipse-green.svg
  public/icons/icon-ellipse-red.svg
  src/app/_components/Notification/AlertItem.tsx
  src/app/_components/Notification/index.tsx
Labels: :sparkles: FEATURE

#101 feat: 헤더 스타일 수정 & 드롭다운 리팩토링 (ST-127)
  src/app/_components/Header/Dropdown.tsx
  src/app/_components/Header/UserDropdown.tsx
  src/app/_components/Header/UserExist.tsx
  src/app/_components/Header/UserNotExist.tsx
  src/app/_components/Header/index.tsx
  src/components/Popover/Content.tsx
  src/components/Popover/Context.ts
  src/components/Popover/Item.tsx
  src/components/Popover/Trigger.tsx
  src/components/Popover/index.tsx
  tailwind.config.ts
Labels: :sparkles: FEATURE

#103 refactor: 에러 페이지 수정(ST-117)
  src/apis/ApiError.ts
  src/apis/axiosInstance.ts
  src/app/(home)/[activityId]/page.tsx
  src/app/error.tsx
Labels: :recycle: REFACTOR

#104 refactor: social login(ST-131)
  src/app/(auth)/layout.tsx
  src/app/(auth)/social/google/page.tsx
  src/app/(auth)/social/kakao/page.tsx
  src/store/kakaoSocialStatusStore.ts
  src/store/socialLoginStore.ts
Labels: :recycle: REFACTOR

#107 fix reservation page(ST-138)
  src/app/(user)/reservations/_components/MyReservationItem.tsx
Labels: :bug: FIX

#105 feat: 로그아웃, 로그인 시 쿼리키 초기화(ST-136)
  src/app/(auth)/signin/page.tsx
  src/app/_components/Header/UserDropdown.tsx
  src/app/_components/Header/index.tsx
Labels: :sparkles: FEATURE

#111 fix: ActivityPage zustand 업데이트에 따라 받는 데이터 수정(예약 시 팝업 오류 해결)(ST-141)
  src/app/(home)/[activityId]/_utils/getCookies.ts
Labels: :bug: FIX

#115 fix: 헤더가 로딩 중일 때는 로그인, 로그아웃 안보이게 수정(ST-144)
  src/app/_components/Header/UserExist.tsx
  src/app/_components/Header/UserPopover.tsx
  src/app/_components/Header/index.tsx
Labels: :bug: FIX

#106 feat: googleAnalytics.tsx 추가(ST-137)
  src/app/layout.tsx
  src/lib/GoogleAnalytics.tsx
Labels: :sparkles: FEATURE

#108 refactor: 무한 스크롤 구현(ST-140)
  src/app/(user)/myactivities/_components/MyActivities.tsx
  src/app/(user)/myactivities/_components/MyActivityItem.tsx
  src/app/(user)/myactivities/page.tsx
Labels: :bug: FIX, :recycle: REFACTOR

#110 fix: 토큰 존재시 auth 페이지 접근 불가(ST-139)
  src/app/(auth)/layout.tsx
Labels: :bug: FIX

#113 refactor: 소셜 로그인 시 유저 정보 수정 비활성화(ST-142)
  src/app/(user)/account/_component/ProfileEditor.tsx
  src/app/(user)/account/page.tsx
Labels: :bug: FIX, :recycle: REFACTOR

#112 refactor: Dropdown 컴파운드 패턴 적용 (ST-135)
  src/app/(home)/search/_components/SortDropdown.tsx
  src/app/(user)/reservations/_components/MyReservations.tsx
  src/app/(user)/reservations/_components/StatusDropdown.tsx
  src/components/Dropdown.tsx
  src/components/Dropdown/Content.tsx
  src/components/Dropdown/Item.tsx
  src/components/Dropdown/Trigger.tsx
  src/components/Dropdown/context.ts
  src/components/Dropdown/index.tsx
Labels: :recycle: REFACTOR

#118 fix: 메인 페이지 모바일, 태블릿 사이즈에서 스타일 깨짐 수정 (ST-147)
  src/app/(home)/_components/ActivityCard.tsx
  src/app/(home)/_components/ActivitySection.tsx
  src/app/(home)/_components/BigActivityCard.tsx
  src/app/(home)/_components/BigActivitySection.tsx
  src/app/(home)/page.tsx
  src/app/(home)/search/_components/ActivityGrid.tsx
Labels: :bug: FIX, :lipstick: STYLE

#116 fix: ActivityPage, 본인의 체험은 이제 예약 불가능함(ST-145)
  src/app/(home)/[activityId]/_components/ReservationSteps/ReservationButton.tsx
Labels: :bug: FIX

#86 feat: 체험 등록페이지 구현 (ST-109)
  package.json
  pnpm-lock.yaml
  public/icons/icon-delete-btn.svg
  src/apis/API.type.ts
  src/app/(user)/_components/Navigation.tsx
  src/app/(user)/myactivities/add/_components/AddInput.tsx
  src/app/(user)/myactivities/add/_components/AddressAutoComplete.tsx
  src/app/(user)/myactivities/add/_components/CategoryDropdown.tsx
  src/app/(user)/myactivities/add/_components/DeleteButton.tsx
  src/app/(user)/myactivities/add/_components/ImageInput.tsx
  src/app/(user)/myactivities/add/_components/SubImagesInput.tsx
  src/app/(user)/myactivities/add/page.tsx
  src/app/_components/Header/UserDropdown.tsx
  src/app/layout.tsx
Labels: :sparkles: FEATURE

#109 feat: reservation status page(ST-31)
  public/icons/left_double_arrow.svg
  public/icons/right_double_arrow.svg
  src/apis/API.type.ts
  src/app/(user)/reservation-status/_components/ExistActivity/Calendar/Calendar.tsx
  src/app/(user)/reservation-status/_components/ExistActivity/Calendar/DateSwitcher.tsx
  src/app/(user)/reservation-status/_components/ExistActivity/Calendar/Day.tsx
  src/app/(user)/reservation-status/_components/ExistActivity/Calendar/ReservationStatusModal/RequestStatus.tsx
  src/app/(user)/reservation-status/_components/ExistActivity/Calendar/ReservationStatusModal/ReservationList/ReservationActionButton.tsx
  src/app/(user)/reservation-status/_components/ExistActivity/Calendar/ReservationStatusModal/ReservationList/ReservationItem.tsx
  src/app/(user)/reservation-status/_components/ExistActivity/Calendar/ReservationStatusModal/ReservationList/ReservationList.tsx
  src/app/(user)/reservation-status/_components/ExistActivity/Calendar/ReservationStatusModal/ReservationList/ReservationStatusView.tsx
  src/app/(user)/reservation-status/_components/ExistActivity/Calendar/ReservationStatusModal/ReservationList/index.ts
  src/app/(user)/reservation-status/_components/ExistActivity/Calendar/ReservationStatusModal/ReservationStatusModal.tsx
  src/app/(user)/reservation-status/_components/ExistActivity/Calendar/ReservationStatusModal/index.ts
  src/app/(user)/reservation-status/_components/ExistActivity/Calendar/index.ts
  src/app/(user)/reservation-status/_components/ExistActivity/ExistActivity.tsx
  src/app/(user)/reservation-status/_components/ExistActivity/MyActivitiesDropdown.tsx
  src/app/(user)/reservation-status/_components/ExistActivity/index.ts
  src/app/(user)/reservation-status/_components/NoExistActivity.tsx
  src/app/(user)/reservation-status/_components/ReservationStatus.tsx
  src/app/(user)/reservation-status/hooks/useCreateCalendar.ts
  src/app/(user)/reservation-status/hooks/usePatchReservationMutation.ts
  src/app/(user)/reservation-status/page.tsx
  src/app/(user)/reservation-status/utils/ReservationMonthDataFormatted.ts
  src/app/(user)/reservation-status/utils/calendar.ts
  src/app/(user)/reservation-status/utils/formatDateToYYYYMMDD.ts
  src/app/(user)/reservation-status/utils/reservationStatus.ts
  src/utils/formatDateToKorean.ts
Labels: :sparkles: FEATURE

#121 refactor: social login 로딩창 수정(ST-146)
  public/images/google.png
  public/images/kakao.png
  src/app/(auth)/social/kakao/page.tsx
  src/app/social/google/page.tsx
  src/app/social/kakao/page.tsx
Labels: :recycle: REFACTOR

#120 fix: ActivityPage, 수정하기 누르면 올바른 url로 이동, 이미지 개수에 따라 layout 수정, 예약 팝업 섬세함 개선(ST-149)
  src/app/(home)/[activityId]/_components/Header/DropdownMenu.tsx
  src/app/(home)/[activityId]/_components/Images.tsx
  src/app/(home)/[activityId]/_components/ReservationSteps/ReservationButton.tsx
  src/app/(home)/[activityId]/_components/ReservationSteps/index.tsx
  src/app/(home)/[activityId]/_hooks/useErrorPopupConfig.ts
  src/app/(home)/[activityId]/_hooks/usePostReservationMutation.ts
Labels: :bug: FIX, :sparkles: FEATURE

#124 fix: 검색 페이지 카테고리 스타일 깨짐 수정 (ST-148)
  src/app/(home)/_components/ActivitySection.tsx
  src/app/(home)/_components/BigActivitySection.tsx
  src/app/(home)/search/_components/TabList/index.tsx
  src/app/(home)/search/page.tsx
  src/components/Swiper/Button.tsx
  src/components/Swiper/Content.tsx
Labels: :bug: FIX, :recycle: REFACTOR

#125 feat: UserPopover 메뉴 수정 (ST-153)
  src/app/_components/Header/UserPopover.tsx
  src/components/Popover/Content.tsx
  src/components/Popover/Item.tsx
Labels: :sparkles: FEATURE

#123 feat: 메타 태그 추가(ST-151)
  src/app/(home)/[activityId]/page.tsx
  src/app/(user)/account/_component/MyAccount.tsx
  src/app/(user)/account/page.tsx
  src/app/(user)/myactivities/add/_components/Add.tsx
  src/app/(user)/myactivities/add/page.tsx
  src/app/(user)/myactivities/edit/[activityId]/page.tsx
  src/app/(user)/myactivities/edit/_components/Edit.tsx
  src/app/(user)/myactivities/page.tsx
  src/app/(user)/reservation-status/page.tsx
  src/app/(user)/reservations/page.tsx
Labels: :sparkles: FEATURE

#122 fix: mypage 오류 수정(ST-150)
  src/app/(user)/myactivities/_components/MyActivityItem.tsx
  src/app/(user)/reservations/_components/MyReservationItem.tsx
  src/app/(user)/reservations/_components/MyReservations.tsx
Labels: :bug: FIX

#127 fix: favicon logo수정(ST-158)
  public/images/logo_small.png
  src/app/favicon.ico
  src/app/layout.tsx
Labels: :recycle: REFACTOR

#128 feat: 로딩스피너 추가(ST-152)
  src/app/(home)/page.tsx
  src/app/(user)/myactivities/_components/MyActivities.tsx
  src/app/(user)/reservations/_components/MyReservations.tsx
  src/utils/LoadingSpinnter.tsx
Labels: :sparkles: FEATURE

#129 refactor: 모달 키 값 받게 수정 그에따라 모든 모달쓰는 페이지 수정(ST-157)
  src/app/(home)/[activityId]/_components/MobileFooter.tsx
  src/app/(home)/[activityId]/_components/ReservationModal.tsx
  src/app/(user)/myactivities/add/_components/AddressAutoComplete.tsx
  src/app/(user)/reservation-status/_components/ExistActivity/Calendar/Day.tsx
  src/app/(user)/reservation-status/_components/ExistActivity/Calendar/ReservationStatusModal/ReservationStatusModal.tsx
  src/app/(user)/reservations/_components/MyReservationItem.tsx
  src/components/Modal.tsx
Labels: :recycle: REFACTOR

#134 style: 페이지 전체적인 스타일 수정 (ST-155)
  src/app/(home)/layout.tsx
  src/app/(home)/page.tsx
  src/app/(home)/search/page.tsx
  src/app/(user)/_components/Navigation.tsx
  src/app/(user)/layout.tsx
  src/app/(user)/myactivities/_components/MyActivities.tsx
  src/app/(user)/myactivities/_components/MyActivityItem.tsx
  src/app/(user)/reservation-status/_components/ExistActivity/Calendar/Calendar.tsx
  src/app/(user)/reservation-status/_components/ExistActivity/ExistActivity.tsx
  src/app/(user)/reservation-status/_components/ReservationStatus.tsx
  src/app/(user)/reservations/_components/MyReservationItem.tsx
  src/app/(user)/reservations/_components/MyReservations.tsx
  src/app/(user)/reservations/page.tsx
  src/app/_components/Header/UserNotExist.tsx
  src/app/_components/Header/index.tsx
  src/components/Modal.tsx
  src/components/Popover/Content.tsx
  src/hooks/useMediaQuery.ts
Labels: :lipstick: STYLE

#132 feat: 미들웨어 추가 빌드 오류 해결 모달 아이콘 수정(ST-161)
  src/app/(auth)/layout.tsx
  src/app/(user)/layout.tsx
  src/app/(user)/reservation-status/page.tsx
  src/components/Modal.tsx
  src/middleware.ts
Labels: :bug: FIX, :sparkles: FEATURE

#133 refactor: 후기 별점 소수점 첫번째자리까지 뜨게함(ST-162)
  src/app/(home)/[activityId]/_components/Review/ReviewDetail.tsx
  src/app/(home)/[activityId]/_hooks/useGetCommentReviewViewModel.ts
  src/app/(home)/[activityId]/_utils/getCommentData.ts
Labels: :recycle: REFACTOR

#135 refactor: main page 리액트 쿼리적용(체험 삭제 시, 즉각 반영되게), 모든 페이지 error이미지 처리, 체험관리 예약내역 팝업 수정(ST-163)
  src/app/(home)/_components/ActivityCard.tsx
  src/app/(home)/_components/ActivitySection.tsx
  src/app/(home)/_components/BigActivityCard.tsx
  src/app/(home)/_components/BigActivitySection.tsx
  src/app/(home)/page.tsx
  src/app/(home)/utils/activitySectionQuery.ts
  src/app/(user)/myactivities/_components/MyActivityItem.tsx
  src/app/(user)/reservations/_components/MyReservationItem.tsx
Labels: :bug: FIX, :recycle: REFACTOR

#136 fix: 지난 날짜는 예약에 안 뜨게 더 엄격히 검사(ST-164)
  src/app/(home)/[activityId]/_components/ReservationSteps/Calendar/CalendarDay.tsx
  src/app/(home)/[activityId]/_utils/createCalendar.ts
Labels: :bug: FIX

#137 fix: notificationData 수정(ST-166)
  src/app/_components/Notification/index.tsx
Labels: :bug: FIX

#138 style: 마우스 커서 안생기는 문제 수정(ST-167)
  src/app/(user)/reservation-status/_components/ExistActivity/Calendar/Day.tsx
  src/app/(user)/reservation-status/hooks/useCreateCalendar.ts
Labels: :lipstick: STYLE

#140 fix: sort 새로고침해도 잘뜸(ST-170)
  src/app/(home)/search/_components/SortDropdown.tsx
Labels: :bug: FIX

#144 fix: 토큰에 sameSite, secure추가(ST-174)
  src/apis/OauthAPI.ts
  src/apis/authAPI.ts
Labels: :bug: FIX

#142 style: 메인 페이지 스타일 깨짐 수정 (ST-171)
  src/app/(home)/_components/ActivityCard.tsx
  src/app/(home)/_components/ActivitySection.tsx
  src/app/(home)/_components/Banner.tsx
  src/app/(home)/_components/BigActivitySection.tsx
  src/app/(home)/layout.tsx
  src/app/(home)/page.tsx
  src/app/(home)/search/page.tsx
  src/app/_components/Header/index.tsx
  src/components/Dropdown/index.tsx
Labels: :lipstick: STYLE

#145 fix: 모달처럼 스크롤 안먹게 수정 팝업도(ST-176)
  src/components/Popup.tsx
Labels: :bug: FIX

#146 fix: notification 오픈 상태 2회 바뀌는 것 수정(ST-177)
  src/app/_components/Notification/index.tsx
Labels: :bug: FIX

#139 refactor: 체험 등록 수정 페이지 메인페이지 반영
  package.json
  pnpm-lock.yaml
  src/app/(user)/myactivities/add/_components/Add.tsx
  src/app/(user)/myactivities/edit/_components/Edit.tsx
Labels: :package: CHORE, :recycle: REFACTOR

#143 fix: 페이지 이동시 스크롤 맨 위로 로드 되게 수정(ST-173)
  src/app/(auth)/layout.tsx
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/(home)/[activityId]/_components/Header/DropdownMenu.tsx
  src/app/(home)/[activityId]/_components/ReservationSteps/ReservationButton.tsx
  src/app/(home)/[activityId]/_hooks/useDeleteActivityMutation.ts
  src/app/_components/Header/UserNotExist.tsx
  src/app/_components/Header/UserPopover.tsx
  src/app/_components/Header/index.tsx
  src/app/social/google/page.tsx
  src/app/social/kakao/page.tsx
Labels: :bug: FIX

#149 style: activity page css 수정
  src/app/(home)/[activityId]/_components/Images.tsx
  src/app/(home)/[activityId]/page.tsx
Labels: :lipstick: STYLE

#150 style: 체험 등록/수정 페이지 스타일 수정 (ST-178)
  src/app/(user)/myactivities/_components/MyActivities.tsx
  src/app/(user)/myactivities/add/_components/Add.tsx
  src/app/(user)/myactivities/edit/_components/Edit.tsx
  src/app/(user)/reservations/_components/MyReservations.tsx
Labels: :lipstick: STYLE

#147 refactor: 체험 등록 수정 페이지 가격 input
  src/app/(user)/myactivities/add/_components/Add.tsx
  src/app/(user)/myactivities/add/_components/NumberInput.tsx
  src/app/(user)/myactivities/edit/_components/Edit.tsx
Labels: :recycle: REFACTOR

#151 fix myactivity add page(ST-182)
  src/app/(user)/myactivities/add/_components/Add.tsx
  src/app/(user)/myactivities/edit/_components/Edit.tsx
Labels: :bug: FIX
