Repository kidnapping-group/TravelMaker, pull requests merged in 2024-07, with the labels that each got.

#2 chore: ST-3-husky
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  .husky/prepare-commit-msg
Labels: :package: CHORE

#3 chore: St 7 palette 테일윈드 palette 추가, 프리티어 import 자동정렬 plugin 추가
  .prettierrc.js
  package-lock.json
  package.json
  pnpm-lock.yaml
  tailwind.config.ts
Labels: :package: CHORE

#4 chore: ST-2-image
  .github/pull_request_template.md
  .husky/pre-commit
  README.md
  package.json
  public/icons/Icon-notification.svg
  public/icons/Icon_moresee.svg
  public/icons/Icon_star_off.svg
  public/icons/Icon_star_on.svg
  public/icons/icon-account.svg
  public/icons/icon-arrow-next-pagination.svg
  public/icons/icon-arrow-prev-pagination.svg
  public/icons/icon-calendar.svg
  public/icons/icon-close-black.svg
  public/icons/icon-close-gary-bold.svg
  public/icons/icon-close-gary.svg
  public/icons/icon-delete-btn.svg
  public/icons/icon-dropdown-small.svg
  public/icons/icon-dropdown.svg
  public/icons/icon-ellipse-blue.svg
  public/icons/icon-ellipse-gary.svg
  public/icons/icon-ellipse-green.svg
  public/icons/icon-ellipse-red.svg
  public/icons/icon-eye-off.svg
  public/icons/icon-eye.svg
  public/icons/icon-facebook.svg
  public/icons/icon-history.svg
  public/icons/icon-instagram.svg
  public/icons/icon-location.svg
  public/icons/icon-pen.svg
  public/icons/icon-reservation.svg
  public/icons/icon-setting.svg
  public/icons/icon-twitter.svg
  public/icons/icon-youtube.svg
  public/icons/icon_search_48px.svg
  public/images/empty.png
  public/images/logo_big.png
  public/images/logo_small.png
Labels: :package: CHORE, :lock: HOLD

#5 chore: ST-17 브레이크 포인트 수정
  tailwind.config.ts
Labels: :package: CHORE

#6 chore: St-5 setting.json => settings.json 수정, trivago 설치, husky의 pre-push파일 코드 삭제
  .eslintrc.json
  .husky/commit-msg
  .husky/pre-commit
  .husky/pre-push
  .husky/prepare-commit-msg
  .prettierrc.js
  .vscode/settings.json
  package.json
  pnpm-lock.yaml
  src/app/layout.tsx
Labels: :package: CHORE

#7 feat: Header 로그아웃 상태의 Header 구현
  src/app/(auth)/signin/page.tsx
  src/app/(auth)/signup/page.tsx
  src/app/_components/Header.tsx
  src/app/layout.tsx
Labels: :sparkles: FEATURE

#16 fix: husky pre-commit lint 오작동 (ST-41)
  .husky/pre-commit
Labels: :bug: FIX
